chore(cicd): separate backend and frontend cicd (#116)

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -1,12 +1,25 @@
 name: CD
 on:
-  push:
-    branches: [main]
+  workflow_call:
+    inputs:
+      app:
+        required: true
+        type: string
+        description: "Which app to continously deploy: frontend or backend"
 
 env:
   REGISTRY: ghcr.io
 
 jobs:
+  verify-input:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Verify input
+        run: |
+          if [[ "${{ inputs.app }}" != "frontend" && "${{ inputs.app }}" != "backend" ]]; then
+            echo "::error::Invalid app input: ${{ inputs.app }}. Must be 'frontend' or 'backend'."
+            exit 1
+          fi
   release:
     outputs:
       tag: ${{ steps.release.outputs.version }}
@@ -23,7 +36,7 @@ jobs:
         with:
           release-type: simple
   build:
-    needs: release
+    needs: [verify-input, release]
     runs-on: ubuntu-latest
     permissions:
       contents: read # needs write permission to push tag and release
@@ -48,78 +61,27 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
 
-      - name: Build and push ${{ matrix.app }} container image
+      - name: Build and push ${{ inputs.app }} container image
         if: ${{ needs.release.outputs.released != 'true' }}
         uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
         with:
-          context: src/${{ matrix.app }}
+          context: src/${{ inputs.app }}
           push: true
           tags: |
-            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:${{ github.sha }}
-            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:latest
+            ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.app }}:${{ github.sha }}
+            ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.app }}:latest
           labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
           platforms: ${{ matrix.platform }}
 
-      - name: Build and push ${{ matrix.app }} container image (RELEASE)
+      - name: Build and push ${{ inputs.app }} container image (RELEASE)
         if: ${{ needs.release.outputs.released == 'true' }}
         uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
         with:
-          context: src/${{ matrix.app }}
+          context: src/${{ inputs.app }}
           push: true
           tags: |
-            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:${{ needs.release.outputs.tag }}
-            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:${{ github.sha }}
-            ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}:latest
+            ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.app }}:${{ needs.release.outputs.tag }}
+            ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.app }}:${{ github.sha }}
+            ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.app }}:latest
           labels: org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
           platforms: ${{ matrix.platform }}
-  # deploy:
-  #  needs: [release, build]
-  #  runs-on: ubuntu-latest
-  #  permissions:
-  #    packages: read # needs write permission to publish Docker image
-  #  env:
-  #    DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
-  #    DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
-  #    DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
-  #    REGISTRY_USERNAME: ${{ github.actor }}
-  #    REGISTRY_TOKEN: ${{ github.token }}
-  #    IMAGE_TAG: ${{ github.sha }}
-  #    ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
-  #    API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
-  #    APP_KEYS: ${{ secrets.APP_KEYS }}
-  #    JWT_SECRET: ${{ secrets.JWT_SECRET }}
-  #    NUXT_API_TOKEN: ${{ secrets.NUXT_API_TOKEN }}
-  #  steps:
-  #    - name: Update deployment
-  #      id: update-deployment
-  #      run: |
-  #        echo "::notice::Setting up SSH key for deployment"
-  #        mkdir -p ~/.ssh
-  #        echo "$DEPLOYMENT_KEY" > ~/.ssh/deployment_key
-  #        chmod 600 ~/.ssh/deployment_key
-
-  #        ssh -i ~/.ssh/deployment_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $DEPLOYMENT_USER@$DEPLOYMENT_HOST << EOF
-  #          echo "::notice::Patch regcred secret"
-  #          kubectl delete secret regcred || true
-  #          kubectl create secret docker-registry regcred \
-  #            --docker-server=ghcr.io \
-  #            --docker-username=$REGISTRY_USERNAME \
-  #            --docker-password=$REGISTRY_TOKEN
-
-  #          echo "::notice::Patch opaque secret"
-  #          kubectl delete secret sam || true
-  #          kubectl create secret generic sam \
-  #            --from-literal=ADMIN_JWT_SECRET="$ADMIN_JWT_SECRET" \
-  #            --from-literal=API_TOKEN_SALT="$API_TOKEN_SALT" \
-  #            --from-literal=APP_KEYS="$APP_KEYS" \
-  #            --from-literal=JWT_SECRET="$JWT_SECRET" \
-  #            --from-literal=NUXT_API_TOKEN="$NUXT_API_TOKEN"
-
-  #          echo "::notice::Patch deployment container images"
-  #          kubectl set image deployment/sam backend=ghcr.io/samdruant-com/website-backend:$IMAGE_TAG frontend=ghcr.io/samdruant-com/website-frontend:$IMAGE_TAG
-
-  #          echo "::notice::Restart deployment"
-  #          kubectl rollout restart deployment/sam
-  #        EOF
-
-  #        echo "::notice::Deployment completed successfully"
